# Site settings
title: Tapas Pal
author:
  name: Tapas Pal
  email: tapas.real@gmail.com
description: "Personal Website"


# generate social links in footer
social_links:
   linkedin: tapas-pal-7b5a88b7
   facebook: tapas.pal.144

minima:
  skin: dark

# Build settings
remote_theme: jekyll/minima
#theme: jekyll/leap-day  
#theme: minima
#remote_theme: alshedivat/al-folio
#  skin: dark

  
