# Site settings
title: Tapas Pal Personal Webpage
author:
  name: Tapas Pal
  email: tapas.real@gmail.com
description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/minima
