name: Update CV

on:
  workflow_dispatch:

  push:
    branches:
      - main

  workflow_run:
    workflows:
      - Deploy
    types:
      - completed

permissions:
  contents: write

jobs:
  update-cv:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout website
        uses: actions/checkout@v4

      - name: Download latest CV
        run: |
          mkdir -p assets/pdf

          curl -L \
          https://github.com/tapaspal9/Tapas-CV-Updated/raw/main/assets/pdf/CV.pdf \
          -o assets/pdf/CV.pdf

      - name: Commit updated CV
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add assets/pdf/CV.pdf

          git commit -m "Update CV PDF" || exit 0

          git push
